// Vertex layout (3, 3, 2, 3, 3)
layout (location = 0) in vec3 position;
layout (location = 1) in vec3 normal;
layout (location = 2) in vec2 texture_coordinate;
layout (location = 3) in vec3 tangent;
layout (location = 4) in vec3 biTangent;

// Camera block
layout (std140, binding = 0) uniform CameraBlock { vec3 position; mat4 view; mat4 projection; } camera;

// Light block
layout (std140, binding = 1) uniform LightBlock { vec3 position; mat4 color; } lights[];

// OpenGl 5 >>> OpenGl 4
